
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile.drupal
    container_name: drupal-t1
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
       DB_HOST: db
       DB_NAME: drupal
       DB_USER: drupaluser
       DB_PASS: drupalpass

       ADMIN_USER: admin
       ADMIN_PASS: admin
       SITE_NAME: "Cloud Computing"
    volumes:
      - drupal-volume:/opt/drupal/ #por padrao o drupal esta em var/www/html

    networks:
      - drupal-network

  mysql:
    image: 'mysql:latest'
    container_name: mysql-t1
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: drupalpass
    
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - drupal-network

volumes:
  drupal-volume:
  mysql-volume:

networks:
  drupal-network:
    driver: bridge
